import { useState } from 'react';
import { AlertCircle, ArrowLeft, ArrowRight, Check, CheckCircle2, CircleHelp, ClipboardCheck, ClipboardList, Clock3, Home, Luggage, MapPin, Package, PackageSearch, ShoppingBag, Stethoscope, Users } from 'lucide-react';
import { changes } from '../data/commandCenterDemo';
import { useApp } from './context';
import { Badge, PageTitle, PersonSwitch, Section, ActionLink, SmallIcon, PackageTile, recordLabel, eventTone } from './shared';
import { caregivers, eventStatus, inboxPersonForNavigation, inboxPersonLabel, locations, packageRelation, people, supplyState, timeNow, tripDays, uid, type Assignment, type Caregiver, type EventStatus, type Location, type PersonId } from './model';

export function TodayPage() {
  const { state, navigate, openEvent, openPackage } = useApp();
  const noReports = state.events.filter((item) => eventStatus(item) === 'NO_REPORT');
  const gaps = state.assignments.filter((item) => item.day === 'Today' && !item.caregiver);
  const low = state.records.filter((item) => !item.archived && supplyState(state, item).status === 'RUNNING LOW');
  const attention = state.inbox.filter((item) => item.status === 'NEEDS REVIEW' || item.status === 'UNPROCESSED').slice(0, 3);
  return <><PageTitle overline="Family Today" title="Everyone's care, in one place" description="A live view of reported events, care coverage, medicines at home, and open questions." />
    <div className="family-strip">{(['dad', 'mom'] as PersonId[]).map((id) => { const events = state.events.filter((item) => item.personId === id); const reported = events.filter((item) => eventStatus(item) !== 'NO_REPORT'); const open = state.inbox.filter((item) => item.personId === id && (item.status === 'NEEDS REVIEW' || item.status === 'UNPROCESSED')).length; return <button className="family-panel" key={id} onClick={() => navigate('people', id)}><span className={`person-avatar ${id}`}>{people[id].initials}</span><span><small>{people[id].name}</small><strong>{people[id].label}</strong><span>{reported.length} of {events.length} events reported</span></span><span className="family-side"><Badge tone={open ? 'warn' : 'good'}>{open ? `${open} needs review` : 'Up to date'}</Badge><ArrowRight size={18} /></span></button>; })}</div>
    <div className="two-columns"><Section title="Care coverage" action={<ActionLink onClick={() => navigate('care')}>Manage</ActionLink>}><div className="coverage-list">{state.assignments.filter((item) => item.day === 'Today').map((item) => <button className="coverage-row" key={item.id} onClick={() => navigate('care')}><span className={`coverage-dot ${item.caregiver ? 'covered' : 'gap'}`} /><strong>{item.period}</strong><span>{people[item.personId].label}</span><b>{item.caregiver ?? 'Nobody assigned'}</b><Badge tone={item.caregiver ? item.acknowledgedAt ? 'good' : 'warn' : 'danger'}>{item.caregiver ? item.acknowledgedAt ? 'Accepted' : 'Pending' : 'Gap'}</Badge></button>)}</div></Section>
    <Section title="Needs attention" action={<ActionLink onClick={() => navigate('inbox')}>Open inbox</ActionLink>}><div className="stack-list">{attention.map((item) => <button className="attention-row" key={item.id} onClick={() => item.target === 'event' && item.targetId ? openEvent(item.targetId) : item.target === 'cabinet' && item.targetId ? openPackage(item.targetId) : navigate(item.target === 'care' ? 'care' : item.target === 'plan' ? 'people' : 'inbox', inboxPersonForNavigation(item))}><SmallIcon icon={AlertCircle} tone="amber" /><span><small>{item.kind} · {inboxPersonLabel(item)}</small><strong>{item.title}</strong></span><ArrowRight size={17} /></button>)}{attention.length === 0 && <p className="empty-state">Nothing needs review right now.</p>}</div></Section></div>
    <div className="summary-band"><div><SmallIcon icon={CircleHelp} tone="amber" /><strong>{noReports.length} no-report event{noReports.length === 1 ? '' : 's'}</strong><small>No one has provided an update. This does not mean missed.</small></div><div><SmallIcon icon={Users} tone="coral" /><strong>{gaps.length} coverage gap{gaps.length === 1 ? '' : 's'}</strong><small>Assign someone to own the routine.</small></div><div><SmallIcon icon={Package} tone="teal" /><strong>{low.length} supply issue{low.length === 1 ? '' : 's'}</strong><small>{low.map((item) => `${item.name}: ${supplyState(state, item).quantity} recorded`).join(', ') || 'No low supply recorded.'}</small></div></div>
    <div className="two-columns"><Section title="No report & upcoming" action={<ActionLink onClick={() => navigate('people', 'dad')}>All events</ActionLink>}><div className="timeline-list">{noReports.slice(0, 4).map((item) => <button className="event-row" key={item.id} onClick={() => openEvent(item.id)}><time>{item.time}</time><span><strong>{recordLabel(state, item.recordId)}</strong><small>{people[item.personId].label} · {item.period}</small></span><Badge tone="warn">No report</Badge></button>)}</div></Section><Section title="Cabinet & activity" action={<ActionLink onClick={() => navigate('cabinet')}>View cabinet</ActionLink>}><div className="activity-list"><p><Package size={17} /> {state.packages.length} packages tracked across the home</p>{state.activity.slice(0, 3).map((item, index) => <p key={`${item}-${index}`}><Clock3 size={17} /> {item}</p>)}</div></Section></div>
  </>;
}

export function PeoplePage() {
  const { state, dispatch, person, navigate, openEvent } = useApp();
  const [tab, setTab] = useState<'current' | 'events' | 'archived'>('current');
  const records = state.records.filter((item) => item.personId === person && item.archived === (tab === 'archived'));
  return <><PageTitle overline="People" title="Family care spaces" description="Medication records stay with the person, including archived history." action={<PersonSwitch />} />
    <div className="person-banner"><span className={`person-avatar large ${person}`}>{people[person].initials}</span><div><small>Family profile</small><h2>{people[person].name}</h2><p>{people[person].age} years · Family-maintained information</p></div><button className="button ghost" onClick={() => navigate('visit', person)}><Stethoscope size={17} /> Visit mode</button></div>
    <div className="tab-row"><button className={tab === 'current' ? 'active' : ''} onClick={() => setTab('current')}>Current medicines</button><button className={tab === 'events' ? 'active' : ''} onClick={() => setTab('events')}>Today's events</button><button className={tab === 'archived' ? 'active' : ''} onClick={() => setTab('archived')}>Archived</button></div>
    {tab === 'events' ? <div className="timeline-list main-events">{state.events.filter((item) => item.personId === person).map((item) => <button className="event-row" key={item.id} onClick={() => openEvent(item.id)}><time>{item.time}</time><span><strong>{recordLabel(state, item.recordId)}</strong><small>{item.period} · {item.instruction}</small></span><Badge tone={eventTone(item)}>{eventStatus(item).replace('_', ' ')}</Badge></button>)}</div> : <div className="record-grid">{records.map((item) => { const supply = supplyState(state, item); return <article className="record-card" key={item.id}><div className="record-top"><SmallIcon icon={Package} /><Badge tone={item.archived ? 'neutral' : item.confirmed ? 'good' : 'warn'}>{item.archived ? 'Archived' : item.confirmed ? 'Confirmed' : 'Needs review'}</Badge></div><h3>{item.name} <span>{item.strength}</span></h3><p>{item.routine}</p><dl><div><dt>Supply</dt><dd>{item.archived ? 'Historical record' : supply.label}</dd></div><div><dt>Source</dt><dd>{item.source}</dd></div></dl>{item.archived && <p className="notice soft">Past record retained. A package at home does not establish a current plan.</p>}</article>; })}</div>}
    <Section title="Care team"><div className="care-team-mini">{caregivers.map((name) => <div key={name}><span className="avatar">{name[0]}</span><strong>{name}</strong><small>{state.assignments.filter((item) => item.day === 'Today' && item.personId === person && item.caregiver === name).length} responsibilities today</small><label>Phone, optional<input type="tel" value={state.contacts[name] ?? ''} onChange={(event) => dispatch({ type: 'SET_CONTACT', caregiver: name, value: event.target.value })} placeholder="Add number" /></label></div>)}</div></Section>
    <Section title="Family-entered information"><label className="allergy-field">Allergies, if provided<input value={state.allergies[person] ?? ''} onChange={(event) => dispatch({ type: 'SET_ALLERGY', personId: person, value: event.target.value })} placeholder="Leave blank if not entered" /></label></Section>
  </>;
}

export function CabinetPage() {
  const { state, person, setDialog, openPackage, navigate } = useApp();
  const [location, setLocation] = useState<Location | 'All'>('All');
  const packages = state.packages.filter((item) => (item.owner === person || item.owner === 'unassigned') && (location === 'All' || item.location === location));
  const current = state.records.filter((item) => item.personId === person && !item.archived);
  const found = current.filter((item) => state.packages.some((pkg) => pkg.recordId === item.id));
  const missing = current.filter((item) => !state.packages.some((pkg) => pkg.recordId === item.id));
  const unmatched = state.packages.filter((item) => item.owner === person && packageRelation(state, item) !== 'CURRENT + FOUND');
  const purchases = state.purchases.filter((item) => item.personId === person);
  return <><PageTitle overline="Digital Medicine Cabinet" title="Medicines in your home" description="Locations, ownership, recorded quantity, and relationship to the current plan." action={<button className="button primary" onClick={() => setDialog('identity')}><PackageSearch size={18} /> Whose medicine is this?</button>} />
    <div className="cabinet-controls"><PersonSwitch /><label className="select-wrap"><MapPin size={17} /><select value={location} onChange={(event) => setLocation(event.target.value as Location | 'All')}><option>All</option>{locations.map((place) => <option key={place}>{place}</option>)}</select></label><button className="button ghost" onClick={() => setDialog('bill')}><ShoppingBag size={17} /> Pharmacy bill</button></div>
    <div className="cabinet-shelves">{(location === 'All' ? locations : [location]).map((place) => { const items = packages.filter((item) => item.location === place); if (!items.length && location === 'All') return null; return <Section key={place} title={place} action={<span className="count-label">{items.length} packages</span>}><div className="shelf-grid">{items.map((item) => <PackageTile item={item} key={item.id} />)}{items.length === 0 && <p className="empty-state">No packages in this location.</p>}</div></Section>; })}</div>
    <Section title="Cabinet vs current plan"><div className="reconcile-grid"><div><h3><CheckCircle2 size={18} /> Current + found at home</h3>{found.map((item) => <p key={item.id}>{item.name} {item.strength}</p>)}{!found.length && <p>None recorded</p>}</div><div><h3><CircleHelp size={18} /> Current + not found at home</h3>{missing.map((item) => <p key={item.id}>{item.name} {item.strength}</p>)}{!missing.length && <p>None recorded</p>}</div><div><h3><AlertCircle size={18} /> Found + not current match</h3>{unmatched.map((item) => <button className="inline-link" key={item.id} onClick={() => openPackage(item.id)}>{item.name} {item.strength} · {packageRelation(state, item)}</button>)}{!unmatched.length && <p>None recorded</p>}</div></div></Section>
    <div className="two-columns"><Section title="Supply tracking"><div className="supply-list">{current.map((item) => { const supply = supplyState(state, item); return <div className="supply-row" key={item.id}><span><strong>{item.name} {item.strength}</strong><small>{supply.quantity === null ? supply.label : `${supply.quantity} recorded${supply.days !== null ? ` · ~${supply.days} days estimated` : ''}`}</small></span><Badge tone={supply.status === 'AVAILABLE' ? 'good' : supply.status === 'RUNNING LOW' ? 'warn' : 'danger'}>{supply.status.replace('_', ' ')}</Badge></div>; })}</div></Section><Section title="Medication purchases" action={<ActionLink onClick={() => setDialog('bill')}>Add bill</ActionLink>}><p className="purchase-total">₹{purchases.reduce((sum, item) => sum + (item.price ?? 0), 0).toLocaleString('en-IN')}</p><small>Confirmed purchase entries only</small>{purchases.slice(0, 4).map((item) => <p className="purchase-line" key={item.id}>{item.date} · {item.name} × {item.quantity} · ₹{item.price ?? '—'}{item.receipt && <button className="inline-link" onClick={() => window.open(item.receipt, '_blank')}>View receipt</button>}</p>)}{!purchases.length && <p className="muted">No purchases recorded yet.</p>}</Section></div>
    {state.travel && state.travel.status !== 'RETURNED' && <button className="travel-callout" onClick={() => navigate('travel')}><Luggage size={21} /><span><strong>Travel pouch is {state.travel.status.toLowerCase()}</strong><small>Check packed medicines and quantities</small></span><ArrowRight size={18} /></button>}
  </>;
}

export function InboxPage() {
  const { state, dispatch, navigate, openEvent, openPackage } = useApp();
  const [filter, setFilter] = useState<'Open' | 'All' | 'Completed'>('Open');
  const items = state.inbox.filter((item) => filter === 'All' || (filter === 'Open' ? ['NEEDS REVIEW', 'UNPROCESSED'].includes(item.status) : ['RESOLVED', 'CONFIRMED'].includes(item.status)));
  function open(item: typeof items[number]) {
    if (item.target === 'event' && item.targetId) openEvent(item.targetId);
    else if (item.target === 'cabinet' && item.targetId && state.packages.some((entry) => entry.id === item.targetId)) openPackage(item.targetId);
    else navigate(item.target === 'cabinet' ? 'cabinet' : item.target === 'care' ? 'care' : item.target === 'visit' ? 'visit' : 'people', inboxPersonForNavigation(item));
  }
  return <><PageTitle overline="Family Medication Inbox" title="New information, one queue" description="Care reports, scans, bills, conflicts, and clarifications remain traceable." action={<div className="segmented">{(['Open', 'All', 'Completed'] as const).map((value) => <button className={filter === value ? 'selected' : ''} key={value} onClick={() => setFilter(value)}>{value}</button>)}</div>} />
    <div className="inbox-list">{items.map((item) => <article className="inbox-item" key={item.id}><SmallIcon icon={item.kind.includes('CONFLICT') ? AlertCircle : ClipboardList} tone={item.kind.includes('CONFLICT') ? 'coral' : 'teal'} /><div><div className="inbox-meta"><span>{item.kind}</span><span>{inboxPersonLabel(item)}</span><span>{item.at}</span></div><h3>{item.title}</h3><p>{item.detail}</p><small>Source: {item.source}</small></div><div className="inbox-actions"><Badge tone={item.status === 'NEEDS REVIEW' || item.status === 'UNPROCESSED' ? 'warn' : 'good'}>{item.status}</Badge><button className="button ghost compact" onClick={() => open(item)}>Open <ArrowRight size={15} /></button>{item.status === 'UNPROCESSED' && <button className="action-link" onClick={() => dispatch({ type: 'SET_INBOX_STATUS', itemId: item.id, status: 'NEEDS REVIEW' })}>Start review</button>}{item.status === 'NEEDS REVIEW' && item.kind !== 'CAREGIVER CONFLICT' && <button className="action-link" onClick={() => dispatch({ type: 'SET_INBOX_STATUS', itemId: item.id, status: 'RESOLVED' })}>Mark reviewed</button>}</div></article>)}{!items.length && <p className="empty-state">No items in this view.</p>}</div>
  </>;
}

function AssignmentRow({ item }: { item: Assignment }) {
  const { state, dispatch } = useApp();
  const [choice, setChoice] = useState<Caregiver>(item.caregiver ?? 'Pavan');
  const available = caregivers.filter((name) => !state.unavailable.some((entry) => entry.caregiver === name && entry.day === item.day));
  const selected = available.includes(choice) ? choice : available[0];
  return <div className="assignment-row"><span className={`coverage-dot ${item.caregiver ? 'covered' : 'gap'}`} /><span><strong>{people[item.personId].label} · {item.period}</strong><small>{item.day}</small></span><span>{item.caregiver ? <><strong>{item.caregiver}</strong><Badge tone={item.acknowledgedAt ? 'good' : 'warn'}>{item.acknowledgedAt ? `Accepted ${item.acknowledgedAt}` : 'Pending acknowledgement'}</Badge></> : <Badge tone="danger">Coverage gap</Badge>}</span>{!item.caregiver ? <div className="inline-assignment"><select value={selected} onChange={(event) => setChoice(event.target.value as Caregiver)}>{available.map((name) => <option key={name}>{name}</option>)}</select><button className="button primary compact" disabled={!selected} onClick={() => dispatch({ type: 'ASSIGN', assignmentId: item.id, caregiver: selected })}>Assign</button></div> : !item.acknowledgedAt ? <button className="button ghost compact" onClick={() => dispatch({ type: 'ACKNOWLEDGE', assignmentId: item.id, at: timeNow() })}>Accept as {item.caregiver}</button> : null}</div>;
}

export function CarePage() {
  const { state, dispatch, navigate, setDialog } = useApp();
  const [day, setDay] = useState<'Today' | 'Tomorrow'>('Today');
  const [unavailableCaregiver, setUnavailableCaregiver] = useState<Caregiver>('Pavan');
  const [unavailableDay, setUnavailableDay] = useState<'Today' | 'Tomorrow'>('Tomorrow');
  const [handoffAssignment, setHandoffAssignment] = useState('assign-dad-eve');
  const [handoffTo, setHandoffTo] = useState<Caregiver>('Pavan');
  const [handoffFrom, setHandoffFrom] = useState<Caregiver>('Mother');
  const affected = state.assignments.filter((item) => item.day === unavailableDay && item.caregiver === unavailableCaregiver);
  const selected = state.assignments.find((item) => item.id === handoffAssignment);
  const handoffCandidates = caregivers.filter((name) => !state.unavailable.some((item) => item.day === selected?.day && item.caregiver === name));
  const effectiveHandoffTo = handoffCandidates.includes(handoffTo) ? handoffTo : handoffCandidates[0];
  return <><PageTitle overline="Care Circle" title="Keep responsibility clear" description="Assignments, acknowledgements, handoffs, and absence coverage for the family." action={<button className="button primary" onClick={() => navigate('visit', 'dad')}><Stethoscope size={18} /> Visit mode</button>} />
    <div className="care-tools"><button onClick={() => navigate('travel')}><Luggage /><strong>Travel with medicines</strong><span>Checklist and travel pouch</span><ArrowRight size={17} /></button><button onClick={() => setDialog('note')}><ClipboardList /><strong>Family observation</strong><span>Record a factual note</span><ArrowRight size={17} /></button><button onClick={() => navigate('postVisit')}><ClipboardCheck /><strong>Post-visit check</strong><span>Guided reconciliation</span><ArrowRight size={17} /></button></div>
    <Section title="Care coverage" action={<div className="segmented"><button className={day === 'Today' ? 'selected' : ''} onClick={() => setDay('Today')}>Today</button><button className={day === 'Tomorrow' ? 'selected' : ''} onClick={() => setDay('Tomorrow')}>Tomorrow</button></div>}><div className="assignment-list">{state.assignments.filter((item) => item.day === day).map((item) => <AssignmentRow key={item.id} item={item} />)}</div></Section>
    <div className="two-columns"><Section title="Unavailable caregiver"><div className="form-grid"><label>Caregiver<select value={unavailableCaregiver} onChange={(event) => setUnavailableCaregiver(event.target.value as Caregiver)}>{caregivers.map((name) => <option key={name}>{name}</option>)}</select></label><label>Day<select value={unavailableDay} onChange={(event) => setUnavailableDay(event.target.value as 'Today' | 'Tomorrow')}><option>Today</option><option>Tomorrow</option></select></label></div><p className="notice amber">{affected.length} responsibilit{affected.length === 1 ? 'y' : 'ies'} would need reassignment. Medication times stay the same.</p><button className="button primary" disabled={!affected.length} onClick={() => dispatch({ type: 'SET_UNAVAILABLE', caregiver: unavailableCaregiver, day: unavailableDay })}>I'm unavailable</button></Section>
      <Section title="Structured handoff"><div className="form-grid"><label>From<select value={handoffFrom} onChange={(event) => setHandoffFrom(event.target.value as Caregiver)}>{caregivers.map((name) => <option key={name}>{name}</option>)}</select></label><label>To<select value={effectiveHandoffTo} onChange={(event) => setHandoffTo(event.target.value as Caregiver)}>{handoffCandidates.map((name) => <option key={name}>{name}</option>)}</select></label></div><label>Responsibility<select value={handoffAssignment} onChange={(event) => setHandoffAssignment(event.target.value)}>{state.assignments.filter((item) => item.day === 'Today').map((item) => <option key={item.id} value={item.id}>{people[item.personId].label} · {item.period}</option>)}</select></label><div className="handoff-brief"><strong>Before accepting</strong><p>Morning: {state.events.filter((item) => item.personId === selected?.personId && item.period === 'Morning' && eventStatus(item) !== 'NO_REPORT').length} updated · Afternoon: {state.events.filter((item) => item.personId === selected?.personId && item.period === 'Afternoon' && eventStatus(item) === 'NO_REPORT').length} no report</p><p>Upcoming: {state.events.filter((item) => item.personId === selected?.personId && item.period === selected?.period).length} recorded events · Supply issues: {state.records.filter((item) => item.personId === selected?.personId && supplyState(state, item).status === 'RUNNING LOW').length}</p><p>Open questions: {state.inbox.filter((item) => item.personId === selected?.personId && item.status === 'NEEDS REVIEW').length}</p></div><button className="button primary" disabled={!effectiveHandoffTo || handoffFrom === effectiveHandoffTo} onClick={() => dispatch({ type: 'CREATE_HANDOFF', handoff: { id: uid('handoff'), from: handoffFrom, to: effectiveHandoffTo, assignmentId: handoffAssignment, status: 'PENDING', at: timeNow() } })}>Send handoff</button></Section></div>
    {state.handoffs.length > 0 && <Section title="Handoffs"><div className="assignment-list">{state.handoffs.map((item) => <div className="handoff-row" key={item.id}><span><strong>{item.from} → {item.to}</strong><small>{state.assignments.find((entry) => entry.id === item.assignmentId)?.period} · {item.at}</small></span><Badge tone={item.status === 'ACKNOWLEDGED' ? 'good' : 'warn'}>{item.status === 'ACKNOWLEDGED' ? `${item.to} acknowledged · ${item.acknowledgedAt}` : 'Pending acknowledgement'}</Badge>{item.status === 'PENDING' && <button className="button ghost compact" onClick={() => dispatch({ type: 'ACCEPT_HANDOFF', handoffId: item.id, at: timeNow() })}>Accept as {item.to}</button>}</div>)}</div></Section>}
    <div className="two-columns"><Section title="Household care load"><div className="load-chart">{(['Morning', 'Afternoon', 'Evening'] as const).map((period) => { const count = state.events.filter((item) => item.period === period).length; return <div key={period}><span>{period}</span><div><i style={{ width: `${Math.max(12, count * 22)}%` }} /></div><b>{count} events</b></div>; })}</div><small>Recorded event volume only. No timing recommendation.</small></Section><Section title="Family observations" action={<ActionLink onClick={() => setDialog('note')}>Add note</ActionLink>}>{state.observations.slice(0, 3).map((item) => <p className="observation-line" key={item.id}><strong>{people[item.personId].label}</strong> · {item.text}<small>{item.caregiver} · {item.at}</small></p>)}{state.observations.length === 0 && <p className="muted">No observations recorded yet.</p>}</Section></div>
    <Section title="Shared activity"><div className="activity-list">{state.activity.slice(0, 8).map((item, index) => <p key={`${item}-${index}`}><Clock3 size={16} /> {item}</p>)}</div></Section>
  </>;
}

export function TravelPage() {
  const { state, dispatch, navigate } = useApp();
  const [personId, setPersonId] = useState<PersonId>('dad');
  const [start, setStart] = useState('2026-09-25');
  const [end, setEnd] = useState('2026-09-29');
  const [quantities, setQuantities] = useState<Record<string, string>>({});
  const [sources, setSources] = useState<Record<string, string>>({});
  const [remaining, setRemaining] = useState<Record<string, string>>({});
  const travel = state.travel;
  const pouchItems = state.packages.filter((item) => item.location === 'Travel Pouch');
  const days = travel ? tripDays(travel.start, travel.end) : tripDays(start, end);
  const records = state.records.filter((item) => item.personId === (travel?.personId ?? personId) && item.confirmed && !item.archived);
  return <><button className="back-button" onClick={() => navigate('care')}><ArrowLeft size={17} /> Care</button><PageTitle overline="Travel with medicines" title="Travel medication checklist" description="Built from confirmed family routines. Check actual packages and packed quantities." />
    {!travel || travel.status === 'RETURNED' ? <section className="form-panel"><div className="form-grid three"><label>Person<select value={personId} onChange={(event) => setPersonId(event.target.value as PersonId)}><option value="dad">Dad</option><option value="mom">Mom</option></select></label><label>Start<input type="date" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>Return<input type="date" value={end} min={start} onChange={(event) => setEnd(event.target.value)} /></label></div><p className="notice soft">{days} calendar days. Only recorded daily events are counted; medication times remain unchanged.</p><button className="button primary" disabled={days < 1} onClick={() => dispatch({ type: 'CREATE_TRAVEL', travel: { personId, start, end, status: 'PLANNING', packed: {} } })}><Luggage size={18} /> Create checklist</button></section> : <><div className="travel-summary"><SmallIcon icon={Luggage} /><div><strong>{people[travel.personId].label} · {travel.start} to {travel.end}</strong><small>{days} days · {Object.keys(travel.packed).length} of {records.length} medicines marked packed</small></div><Badge tone={travel.status === 'ACTIVE' ? 'good' : 'warn'}>{travel.status}</Badge></div>
      <Section title="Packing checklist"><div className="travel-list">{records.map((item) => {
        const required = item.dailyEvents > 0 ? item.dailyEvents * days : null;
        const packed = travel.packed[item.id];
        const available = state.packages.filter((pkg) => pkg.recordId === item.id && pkg.location !== 'Travel Pouch');
        const source = available.find((pkg) => pkg.id === sources[item.id]);
        const invalidQuantity = !quantities[item.id] || !Number.isInteger(Number(quantities[item.id])) || Number(quantities[item.id]) < 1 || (source?.quantity !== null && source?.quantity !== undefined && Number(quantities[item.id]) > source.quantity);
        return <article className="travel-item" key={item.id}><SmallIcon icon={Package} /><div><h3>{item.name} {item.strength}</h3><p>{required === null ? 'Non-daily routine: review the confirmed record' : `${required} recorded events during trip`}</p><small>{packed !== undefined && packed !== null ? `${packed} packed · quantity confirmed` : 'Packed quantity not confirmed'}</small></div><div className="pack-controls"><input aria-label={`Packed quantity for ${item.name}`} type="number" min="1" placeholder="Qty" value={quantities[item.id] ?? ''} disabled={packed !== undefined} onChange={(event) => setQuantities({ ...quantities, [item.id]: event.target.value })} /><select aria-label={`Package for ${item.name}`} value={sources[item.id] ?? ''} disabled={packed !== undefined} onChange={(event) => setSources({ ...sources, [item.id]: event.target.value })}><option value="">No package selected</option>{available.map((pkg) => <option value={pkg.id} key={pkg.id}>{pkg.location} · {pkg.shelf}</option>)}</select><button className="button primary compact" disabled={packed !== undefined || invalidQuantity} onClick={() => dispatch({ type: 'PACK_TRAVEL', recordId: item.id, quantity: Number(quantities[item.id]), packageId: sources[item.id] || undefined })}>{packed !== undefined ? 'Packed' : 'Mark packed'}</button></div></article>;
      })}</div></Section>
      <Section title="Return from trip"><p className="muted">Confirm the quantity remaining in each pouch package before returning it to the cabinet.</p><div className="return-list">{pouchItems.map((item) => <label key={item.id}>{item.name} {item.strength}<input type="number" min="0" placeholder="Remaining" value={remaining[item.id] ?? ''} onChange={(event) => setRemaining({ ...remaining, [item.id]: event.target.value })} /></label>)}</div><div className="travel-footer"><p>Remaining quantities return to their previous home location.</p><button className="button ghost" disabled={pouchItems.some((item) => remaining[item.id] === undefined || remaining[item.id] === '' || Number(remaining[item.id]) < 0 || !Number.isInteger(Number(remaining[item.id])))} onClick={() => dispatch({ type: 'RETURN_TRAVEL', remaining: Object.fromEntries(pouchItems.map((item) => [item.id, Number(remaining[item.id])])) })}><Home size={17} /> Return to cabinet</button></div></Section></>}
  </>;
}

export function VisitPage() {
  const { state, person, navigate } = useApp();
  const records = state.records.filter((item) => item.personId === person && item.confirmed && !item.archived);
  const events = state.events.filter((item) => item.personId === person);
  const unresolved = state.inbox.filter((item) => item.personId === person && ['NEEDS REVIEW', 'UNPROCESSED'].includes(item.status));
  const mismatches = state.packages.filter((item) => item.owner === person && packageRelation(state, item) !== 'CURRENT + FOUND');
  const questions = unresolved.filter((item) => item.kind === 'PRESCRIPTION' || item.kind === 'PACKAGE MATCH' || item.kind === 'POST-VISIT INSTRUCTION');
  return <div className="visit-mode"><button className="back-button" onClick={() => navigate('care')}><ArrowLeft size={17} /> Care</button><div className="visit-header"><p className="overline">Family-maintained information · Verify with a healthcare professional</p><h1>{people[person].label}'s clinic visit</h1><div className="visit-actions"><PersonSwitch /><button className="button primary" onClick={() => navigate('postVisit')}><ClipboardCheck size={17} /> Start post-visit check</button></div></div>
    <div className="visit-grid"><Section title="Current confirmed medication record">{records.map((item) => <p className="visit-line" key={item.id}><strong>{item.name} {item.strength}</strong><span>{item.routine}</span><small>{item.source}</small></p>)}</Section><Section title="Recent changes">{person === 'dad' ? changes.map((item) => <p className="visit-line" key={item.id}><strong>{item.medicine}</strong><span>{item.type}: {item.detail}</span></p>) : <p className="muted">No recent changes recorded.</p>}</Section><Section title="Medication event summary"><div className="visit-stat-row">{(['TAKEN', 'MISSED', 'UNSURE', 'NO_REPORT', 'NOT_AVAILABLE', 'CONFLICT'] as EventStatus[]).map((status) => <div key={status}><b>{events.filter((item) => eventStatus(item) === status).length}</b><small>{status.replace('_', ' ')}</small></div>)}</div></Section><Section title="Unavailable medication events">{events.filter((item) => eventStatus(item) === 'NOT_AVAILABLE').map((item) => <p className="visit-line" key={item.id}>{recordLabel(state, item.recordId)} · {item.time} · {item.reports[item.reports.length - 1]?.context ?? 'No context recorded'}</p>)}{!events.some((item) => eventStatus(item) === 'NOT_AVAILABLE') && <p className="muted">None reported.</p>}</Section><Section title="Unresolved questions">{unresolved.map((item) => <p className="visit-line" key={item.id}><strong>{item.title}</strong><span>{item.detail}</span></p>)}{!unresolved.length && <p className="muted">None recorded.</p>}</Section><Section title="Family observations">{state.observations.filter((item) => item.personId === person).map((item) => <p className="visit-line" key={item.id}><span>{item.text}</span><small>{item.caregiver} · {item.at}</small></p>)}{!state.observations.some((item) => item.personId === person) && <p className="muted">None recorded.</p>}</Section><Section title="Package mismatches">{mismatches.map((item) => <p className="visit-line" key={item.id}><strong>{item.name} {item.strength}</strong><span>{packageRelation(state, item)}</span></p>)}{!mismatches.length && <p className="muted">None recorded.</p>}</Section><Section title="Caregiver questions">{questions.map((item) => <p className="visit-line" key={item.id}>{item.detail}</p>)}{!questions.length && <p className="muted">None recorded.</p>}</Section></div><p className="visit-disclaimer">Family-maintained summary of recorded information. Not an official medical record or medical advice.</p>
  </div>;
}

const steps = ['Add instructions', 'Compare previous state', 'Review changes', 'Check open questions', 'Compare home cabinet', 'Confirm understanding', 'Update confirmed routine', 'Archive superseded record', 'Update responsibilities'];
export function PostVisitPage() {
  const { state, dispatch, navigate, person } = useApp();
  const [step, setStep] = useState(0);
  const [maxReached, setMaxReached] = useState(0);
  const [instruction, setInstruction] = useState('');
  const [understood, setUnderstood] = useState(false);
  const [recordId, setRecordId] = useState(state.records.find((item) => item.personId === person && !item.archived)?.id ?? '');
  const [routine, setRoutine] = useState('');
  const [daily, setDaily] = useState(2);
  const [confirmed, setConfirmed] = useState(false);
  const [archiveId, setArchiveId] = useState('');
  const current = state.records.filter((item) => item.personId === person && !item.archived);
  return <><button className="back-button" onClick={() => navigate('visit', person)}><ArrowLeft size={17} /> Visit mode</button><PageTitle overline="Guided reconciliation" title="Post-visit check" description="Move through new information together. Routine changes require explicit family confirmation." />
    <div className="wizard"><aside className="wizard-steps">{steps.map((label, index) => <button key={label} className={index === step ? 'active' : index < step ? 'done' : ''} disabled={index > maxReached} onClick={() => setStep(index)}><span>{index < step ? <Check size={15} /> : index + 1}</span>{label}</button>)}</aside><section className="wizard-main"><p className="overline">Step {step + 1} of 9</p><h2>{steps[step]}</h2>
      {step === 0 && <><p>Add new instructions for review. They will not change a routine automatically.</p><textarea value={instruction} onChange={(event) => setInstruction(event.target.value)} placeholder="Enter the exact instruction or question" /><button className="button ghost" disabled={!instruction.trim()} onClick={() => { dispatch({ type: 'ADD_INBOX', item: { id: uid('inbox'), kind: 'POST-VISIT INSTRUCTION', title: 'New visit instruction needs review', detail: instruction.trim(), source: 'Caregiver entry after visit', personId: person, at: timeNow(), status: 'NEEDS REVIEW', target: 'plan' } }); setInstruction(''); }}>Add for review</button></>}
      {step === 1 && <div className="check-list">{current.map((item) => <p key={item.id}><strong>{item.name} {item.strength}</strong><span>{item.routine}</span></p>)}</div>}
      {step === 2 && <div className="check-list">{person === 'dad' ? changes.map((item) => <p key={item.id}><strong>{item.type}: {item.medicine}</strong><span>{item.detail}</span></p>) : <p>No changes recorded for Mom.</p>}</div>}
      {step === 3 && <div className="check-list">{state.inbox.filter((item) => item.personId === person && ['NEEDS REVIEW', 'UNPROCESSED'].includes(item.status)).map((item) => <p key={item.id}><strong>{item.title}</strong><span>{item.detail}</span></p>)}</div>}
      {step === 4 && <div className="check-list">{state.packages.filter((item) => item.owner === person).map((item) => <p key={item.id}><strong>{item.name} {item.strength}</strong><span>{packageRelation(state, item)} · {item.location}</span></p>)}</div>}
      {step === 5 && <label className="checkbox-row"><input type="checkbox" checked={understood} onChange={(event) => setUnderstood(event.target.checked)} /> The family reviewed the new instructions and open questions together.</label>}
      {step === 6 && <><p>Update a routine only when the instruction is confirmed. Historical events are retained.</p><label>Medication<select value={recordId} onChange={(event) => { setRecordId(event.target.value); setRoutine(''); setConfirmed(false); }}>{current.map((item) => <option value={item.id} key={item.id}>{item.name} {item.strength}</option>)}</select></label><p className="notice soft">Current: {state.records.find((item) => item.id === recordId)?.routine}</p><label>Confirmed routine text<input value={routine} onChange={(event) => setRoutine(event.target.value)} placeholder="Exact confirmed routine" /></label><label>Recorded daily events<input type="number" min="0" max="8" value={daily} onChange={(event) => setDaily(Number(event.target.value))} /></label><label className="checkbox-row"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /> Confirmed from the visit instructions</label><button className="button primary" disabled={!routine.trim() || !confirmed} onClick={() => { dispatch({ type: 'UPDATE_ROUTINE', recordId, routine: routine.trim(), dailyEvents: daily }); setRoutine(''); setConfirmed(false); }}>Confirm routine update</button></>}
      {step === 7 && <><p>Archive only when the family confirmed a record is no longer current. History remains available.</p><label>Medication<select value={archiveId} onChange={(event) => setArchiveId(event.target.value)}><option value="">Choose only if confirmed</option>{current.map((item) => <option value={item.id} key={item.id}>{item.name} {item.strength}</option>)}</select></label><button className="button ghost" disabled={!archiveId} onClick={() => { dispatch({ type: 'ARCHIVE_RECORD', recordId: archiveId }); setArchiveId(''); }}>Archive confirmed record</button></>}
      {step === 8 && <><p>Review who is responsible. Assignments change care ownership, not medication timing.</p><div className="assignment-list">{state.assignments.filter((item) => item.day === 'Today' && item.personId === person).map((item) => <AssignmentRow key={item.id} item={item} />)}</div></>}
      <div className="wizard-footer"><button className="button ghost" disabled={step === 0} onClick={() => setStep(step - 1)}>Back</button>{step < 8 ? <button className="button primary" disabled={step === 5 && !understood} onClick={() => { setStep(step + 1); setMaxReached(Math.max(maxReached, step + 1)); }}>Continue <ArrowRight size={17} /></button> : <button className="button primary" disabled={!understood} onClick={() => { dispatch({ type: 'ADD_INBOX', item: { id: uid('inbox'), kind: 'POST-VISIT', title: 'Post-visit check completed', detail: 'The family reviewed records, questions, cabinet, and care coverage.', source: 'Guided check', personId: person, at: timeNow(), status: 'CONFIRMED', target: 'visit' } }); navigate('care'); }}>Finish check <Check size={17} /></button>}</div>
    </section></div>
  </>;
}
